---
# ###################################################################
#
# This is the template that orchestrates the setup and install 
#
# ###################################################################
 
# sudo apt-get update
- name: SETUP | Update apt packages
  become: yes
  apt:
    update_cache: yes
  tags:
    - system

# sudo apt-get autoclean
- name: SETUP | Remove useless apt packages from the cache
  become: yes
  apt:
    autoclean: yes
  tags:
    - system

# Import prerequisites tasks
- name: SETUP | Import prerequisites tasks
  become: yes
  include_tasks: prereq.yml
  tags:
    - prerequisites

# Import elastic tasks
- name: SETUP | Import elasticsearch tasks
  include_tasks: elasticsearch.yml
  tags:
    - elk

# Import kibana tasks
- name: SETUP | Import kibana tasks
  include_tasks: kibana.yml
  tags:
    - elk

# Usually logstash is being used with elasticsearch and kibana
# to form the so called elk stack. I am including but not deploying
# a logstash installation playbook

# # Import logstash tasks
# - name: SETUP | Import logstash tasks
#   include_tasks: logstash.yml
#   tags:
#     - elk

# Import nginx tasks
- name: SETUP | Import nginx tasks
  include_tasks: nginx.yml
  tags:
    - nginx

# sudo apt-get autoremove
- name: SETUP | Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
  tags:
    - system